'use strict';

const PaytmChecksum = require('../checksum');
const { buildUrl, formatDateToDdMmYyyy, trimStr, deepConvertDates } = require('../utils');

const perform = async (z, bundle) => {
  const keySecret = bundle.authData.keySecret;
  const mid = bundle.authData.merchantId;

  const body = { mid };

  const merchantRequestId = trimStr(bundle.inputData.merchantRequestId);
  if (merchantRequestId) body.merchantRequestId = merchantRequestId;

  const linkId = trimStr(bundle.inputData.linkId);
  if (linkId) body.linkId = linkId;

  const customerName = trimStr(bundle.inputData.customerName);
  if (customerName) body.customerName = customerName;

  const customerPhone = trimStr(bundle.inputData.customerPhone);
  if (customerPhone) body.customerPhone = customerPhone;

  const customerEmail = trimStr(bundle.inputData.customerEmail);
  if (customerEmail) body.customerEmail = customerEmail;

  const paymentStatus = trimStr(bundle.inputData.paymentStatus);
  if (paymentStatus) body.paymentStatus = paymentStatus;

  const resellerId = trimStr(bundle.inputData.resellerId);
  if (resellerId) body.resellerId = resellerId;

  const resellerName = trimStr(bundle.inputData.resellerName);
  if (resellerName) body.resellerName = resellerName;

  // linkTypeMultiple: Zapier multi-select sends an array; legacy comma-separated string supported for back-compat
  const linkTypeInput = bundle.inputData.linkTypeMultiple;
  let linkTypes = [];
  if (Array.isArray(linkTypeInput)) {
    linkTypes = linkTypeInput.map((s) => String(s).trim()).filter(Boolean);
  } else if (typeof linkTypeInput === 'string' && linkTypeInput.trim() !== '') {
    linkTypes = linkTypeInput.split(',').map((s) => s.trim()).filter(Boolean);
  }
  if (linkTypes.length > 0) body.linkTypeMultiple = linkTypes;

  const fromDateRaw = bundle.inputData.filterFromDate;
  const toDateRaw = bundle.inputData.filterToDate;
  const isActiveRaw = bundle.inputData.filterIsActive;
  const searchFilter = {};
  if (fromDateRaw) searchFilter.fromDate = formatDateToDdMmYyyy(fromDateRaw) || trimStr(fromDateRaw);
  if (toDateRaw) searchFilter.toDate = formatDateToDdMmYyyy(toDateRaw) || trimStr(toDateRaw);
  // "Only active links" toggle: when ON, restrict to active; when OFF, no filter (don't send isActive=false to Paytm)
  if (isActiveRaw === true || isActiveRaw === 'true') {
    searchFilter.isActive = true;
  }
  if (Object.keys(searchFilter).length > 0) body.searchFilterRequestBody = searchFilter;

  const signature = await PaytmChecksum.generateSignature(JSON.stringify(body), keySecret);
  const payload = {
    body,
    head: { tokenType: 'AES', signature, channelId: 'WEB' },
  };

  const url = buildUrl(bundle.authData.environment, '/link/fetch');

  const response = await z.request({
    method: 'POST',
    url,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  const data = response.json;
  const resultBody = data.body || data;
  const links = resultBody.links || resultBody.linkList || resultBody.data;

  if (Array.isArray(links)) {
    const items = links.map((l, i) => ({ id: l.linkId || l.merchantRequestId || i, ...l }));
    return deepConvertDates(items);
  }
  return deepConvertDates([{ id: 'result', ...resultBody }]);
};

module.exports = {
  key: 'fetch_all_payment_links',
  noun: 'Payment Link',
  display: {
    label: 'Fetch All Payment Links',
    description: 'Fetch all payment links within a date range.',
  },
  operation: {
    cleanInputData: false,
    inputFields: [
      {
        key: 'linkId',
        label: 'Link ID',
        type: 'string',
        required: false,
        helpText: 'Unique identifier for each payment link.',
      },
      {
        key: 'linkTypeMultiple',
        label: 'Link type',
        type: 'string',
        required: false,
        list: true,
        choices: { FIXED: 'Fixed', GENERIC: 'Generic' },
        helpText: 'Link type to fetch.',
      },
      {
        key: 'paymentStatus',
        label: 'Payment status',
        type: 'string',
        required: false,
        choices: {
          EXPIRED: 'Expired',
          INIT: 'Initiated',
          PAID: 'Paid',
          PENDING: 'Pending',
        },
        default: 'PENDING',
        helpText: 'Fetch links based on payment status.',
      },
      {
        key: 'merchantRequestId',
        label: 'Merchant request ID',
        type: 'string',
        required: false,
        helpText: 'Unique ID generated by merchant.',
      },
      {
        key: 'filterIsActive',
        label: 'Only active links',
        type: 'boolean',
        required: false,
        default: 'false',
        helpText: 'Fetch only active links.',
      },
      {
        key: 'filterFromDate',
        label: 'Start date',
        type: 'datetime',
        required: false,
        helpText: 'Start date to fetch payment links.',
      },
      {
        key: 'filterToDate',
        label: 'End date',
        type: 'datetime',
        required: false,
        helpText: 'End date to fetch payment links.',
      },
      {
        key: 'customerName',
        label: 'Customer name',
        type: 'string',
        required: false,
        helpText: "Fetch links using customer's name.",
      },
      {
        key: 'customerEmail',
        label: 'Customer email ID',
        type: 'string',
        required: false,
        helpText: "Fetch links using customer's email ID.",
      },
      {
        key: 'customerPhone',
        label: 'Customer mobile',
        type: 'string',
        required: false,
        helpText: "Fetch links using customer's mobile number.",
      },
      {
        key: 'resellerId',
        label: 'Reseller ID',
        type: 'string',
        required: false,
        helpText: 'Fetch links based on reseller ID.',
      },
      {
        key: 'resellerName',
        label: 'Reseller name',
        type: 'string',
        required: false,
        helpText: 'Fetch links based on reseller name.',
      },
    ],
    perform,
    outputFields: [
      { key: 'id', label: 'ID' },
      { key: 'linkId', label: 'Link ID' },
      { key: 'merchantRequestId', label: 'Merchant Request ID' },
      { key: 'linkName', label: 'Link Name' },
      { key: 'linkType', label: 'Link Type' },
      { key: 'amount', label: 'Amount' },
      { key: 'paymentStatus', label: 'Payment Status' },
      { key: 'linkUrl', label: 'Payment URL' },
    ],
    sample: {
      id: 'LINK123',
      linkId: 'LINK123',
      linkName: 'Test Payment Link',
      linkType: 'FIXED',
      amount: '500.00',
      paymentStatus: 'INIT',
    },
  },
};
